# Generated by Django 5.0.2 on 2024-02-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='puchaser',
            new_name='purchaser',
        ),
    ]
